# Generated by Django 4.2.10 on 2024-02-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Player.', max_length=100)),
                ('Height', models.IntegerField(verbose_name='enter your height')),
                ('Weight', models.IntegerField(verbose_name='enter your weight')),
                ('age', models.IntegerField(verbose_name='enter your age')),
            ],
        ),
    ]
